name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shoptok-backend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Build backend
        run: npm run build
      - name: Deploy Backend
        run: |
          echo "Deploy backend to your cloud or container here"
          # Example: kubectl apply -f ../k8s/deployment.yaml

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shoptok-frontend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Build frontend
        run: npm run build
      - name: Deploy Frontend
        run: |
          echo "Deploy frontend to your cloud or CDN here"
          # Example: rsync or cloud CLI commands

  ml-pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shoptok-ml
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run ML training
        run: python src/training/train_friend_recommender.py && python src/training/train_product_recommender.py
      - name: Deploy ML service
        run: |
          echo "Deploy ML serving API here"
          # Example: kubectl apply -f ../k8s/ml-deployment.yaml
