apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoptok-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoptok-backend
  template:
    metadata:
      labels:
        app: shoptok-backend
    spec:
      containers:
      - name: backend
        image: your-docker-repo/shoptok-backend:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: shoptok-secrets
